data:
 test_size: 0.2
 random_state: 42
 path_to_data: 'ai_vs_human_text_2026.csv'

train_data:
 train_path: 'data\raw\raw_train_data.csv'

test_data:
 test_path: 'data\raw\raw_test_data.csv'

preprocessed_train_data:
 train: 'data\preprocessed\train.csv'

preprocessed_test_data:
 test: 'data\preprocessed\test.csv'

smote:
 random_state: 42
 k_neighbors: 5

vectorizer:
 max_features: 5000
 max_df: 0.8
 ngram_range: [1,2]

pickle:
 model_path: 'rf_model.pkl'
 vectorizer_path: 'vectorizer.pkl'

